In [ ]:
 import pandas as pd

In [ ]:
df=pd.read_csv("/content/Political Sentiment Analysis (Train).csv")

In [ ]:
print(df)

     tweet_id         user_handle            timestamp  \
0           1            @user123  2024-11-03 08:45:00
1           2        @politicsFan  2024-11-03 09:15:23
2           3      @greenAdvocate  2024-11-03 10:05:45
3           4         @indieVoice  2024-11-03 11:20:10
4           5       @libertyLover  2024-11-03 12:35:55
..        ...                 ...                  ...
495       496           @user1067  2024-02-10 08:50:30
496       497          @econTalk7  2024-02-10 09:15:55
497       498    @greenFutureNow7  2024-02-10 10:05:30
498       499  @indiePerspective7  2024-02-10 11:35:25
499       500  @libertyMovement13  2024-02-10 12:20:45

                                            tweet_text       candidate  \
0    Excited to see Kamala Harris leading the Democ...   Kamala Harris
1    Donald Trump's policies are the best for our e...    Donald Trump
2    Jill Stein's environmental plans are exactly w...      Jill Stein
3    Robert Kennedy offers a fresh perspective outs...  Robert Kennedy
4    Chase Oliver's libertarian stance promotes tru...    Chase Oliver
..                                                 ...             ...
495  Kamala Harris is a symbol of progressive leade...   Kamala Harris
496  Trump's economic strategies are showing mixed ...    Donald Trump
497  Jill Stein's solar projects are leading the wa...      Jill Stein
498  Robert Kennedy offers pragmatic solutions outs...  Robert Kennedy
499  Chase Oliver is expanding his base among liber...    Chase Oliver

                 party  retweets  likes sentiment
0     Democratic Party       120    450  positive
1     Republican Party        85    300  positive
2          Green Party        60    200  positive
3          Independent        40    150   neutral
4    Libertarian Party        30    120  positive
..                 ...       ...    ...       ...
495   Democratic Party        95    360  positive
496   Republican Party       100    440   neutral
497        Green Party        75    240  positive
498        Independent        18     85   neutral
499  Libertarian Party        40    160  positive

[500 rows x 9 columns]

In [ ]:
print(df.head())

   tweet_id     user_handle            timestamp  \
0         1        @user123  2024-11-03 08:45:00
1         2    @politicsFan  2024-11-03 09:15:23
2         3  @greenAdvocate  2024-11-03 10:05:45
3         4     @indieVoice  2024-11-03 11:20:10
4         5   @libertyLover  2024-11-03 12:35:55

                                          tweet_text       candidate  \
0  Excited to see Kamala Harris leading the Democ...   Kamala Harris
1  Donald Trump's policies are the best for our e...    Donald Trump
2  Jill Stein's environmental plans are exactly w...      Jill Stein
3  Robert Kennedy offers a fresh perspective outs...  Robert Kennedy
4  Chase Oliver's libertarian stance promotes tru...    Chase Oliver

               party  retweets  likes sentiment
0   Democratic Party       120    450  positive
1   Republican Party        85    300  positive
2        Green Party        60    200  positive
3        Independent        40    150   neutral
4  Libertarian Party        30    120  positive

In [ ]:
print(df.shape)

(500, 9)

In [ ]:
print(df.tail())

     tweet_id         user_handle            timestamp  \
495       496           @user1067  2024-02-10 08:50:30
496       497          @econTalk7  2024-02-10 09:15:55
497       498    @greenFutureNow7  2024-02-10 10:05:30
498       499  @indiePerspective7  2024-02-10 11:35:25
499       500  @libertyMovement13  2024-02-10 12:20:45

                                            tweet_text       candidate  \
495  Kamala Harris is a symbol of progressive leade...   Kamala Harris
496  Trump's economic strategies are showing mixed ...    Donald Trump
497  Jill Stein's solar projects are leading the wa...      Jill Stein
498  Robert Kennedy offers pragmatic solutions outs...  Robert Kennedy
499  Chase Oliver is expanding his base among liber...    Chase Oliver

                 party  retweets  likes sentiment
495   Democratic Party        95    360  positive
496   Republican Party       100    440   neutral
497        Green Party        75    240  positive
498        Independent        18     85   neutral
499  Libertarian Party        40    160  positive

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tweet_id     500 non-null    int64
 1   user_handle  500 non-null    object
 2   timestamp    500 non-null    object
 3   tweet_text   500 non-null    object
 4   candidate    500 non-null    object
 5   party        500 non-null    object
 6   retweets     500 non-null    int64
 7   likes        500 non-null    int64
 8   sentiment    500 non-null    object
dtypes: int64(3), object(6)
memory usage: 35.3+ KB
None

In [ ]:
print(df.describe())

         tweet_id    retweets       likes
count  500.000000  500.000000  500.000000
mean   250.500000   64.236000  248.920000
std    144.481833   27.715349  120.562034
min      1.000000   18.000000   85.000000
25%    125.750000   40.000000  150.000000
50%    250.500000   70.000000  225.000000
75%    375.250000   90.000000  340.000000
max    500.000000  120.000000  500.000000

In [ ]:
df

,tweet_id,user_handle,timestamp,tweet_text,candidate,party,retweets,likes,sentiment
0,1,@user123,2024-11-03 08:45:00,Excited to see Kamala Harris leading the Democ...,Kamala Harris,Democratic Party,120,450,positive
1,2,@politicsFan,2024-11-03 09:15:23,Donald Trump's policies are the best for our e...,Donald Trump,Republican Party,85,300,positive
2,3,@greenAdvocate,2024-11-03 10:05:45,Jill Stein's environmental plans are exactly w...,Jill Stein,Green Party,60,200,positive
3,4,@indieVoice,2024-11-03 11:20:10,Robert Kennedy offers a fresh perspective outs...,Robert Kennedy,Independent,40,150,neutral
4,5,@libertyLover,2024-11-03 12:35:55,Chase Oliver's libertarian stance promotes tru...,Chase Oliver,Libertarian Party,30,120,positive
...,...,...,...,...,...,...,...,...,...
495,496,@user1067,2024-02-10 08:50:30,Kamala Harris is a symbol of progressive leade...,Kamala Harris,Democratic Party,95,360,positive
496,497,@econTalk7,2024-02-10 09:15:55,Trump's economic strategies are showing mixed ...,Donald Trump,Republican Party,100,440,neutral
497,498,@greenFutureNow7,2024-02-10 10:05:30,Jill Stein's solar projects are leading the wa...,Jill Stein,Green Party,75,240,positive
498,499,@indiePerspective7,2024-02-10 11:35:25,Robert Kennedy offers pragmatic solutions outs...,Robert Kennedy,Independent,18,85,neutral
499,500,@libertyMovement13,2024-02-10 12:20:45,Chase Oliver is expanding his base among liber...,Chase Oliver,Libertarian Party,40,160,positive

In [ ]:
numeric_cols=df.select_dtypes(include=['float64','int64']).columns

In [ ]:
for col in  numeric_cols:
  df[col]=df[col].fillna(df[col].mean())

In [ ]:
df=df.drop_duplicates()

In [ ]:
print(df.head())

   tweet_id     user_handle            timestamp  \
0         1        @user123  2024-11-03 08:45:00
1         2    @politicsFan  2024-11-03 09:15:23
2         3  @greenAdvocate  2024-11-03 10:05:45
3         4     @indieVoice  2024-11-03 11:20:10
4         5   @libertyLover  2024-11-03 12:35:55

                                          tweet_text       candidate  \
0  Excited to see Kamala Harris leading the Democ...   Kamala Harris
1  Donald Trump's policies are the best for our e...    Donald Trump
2  Jill Stein's environmental plans are exactly w...      Jill Stein
3  Robert Kennedy offers a fresh perspective outs...  Robert Kennedy
4  Chase Oliver's libertarian stance promotes tru...    Chase Oliver

               party  retweets  likes sentiment
0   Democratic Party       120    450  positive
1   Republican Party        85    300  positive
2        Green Party        60    200  positive
3        Independent        40    150   neutral
4  Libertarian Party        30    120  positive

In [ ]:
print(df.shape)

(500, 9)

In [ ]:
print(df.isnull().sum)

<bound method DataFrame.sum of      tweet_id  user_handle  timestamp  tweet_text  candidate  party  retweets  \
0       False        False      False       False      False  False     False
1       False        False      False       False      False  False     False
2       False        False      False       False      False  False     False
3       False        False      False       False      False  False     False
4       False        False      False       False      False  False     False
..        ...          ...        ...         ...        ...    ...       ...
495     False        False      False       False      False  False     False
496     False        False      False       False      False  False     False
497     False        False      False       False      False  False     False
498     False        False      False       False      False  False     False
499     False        False      False       False      False  False     False

     likes  sentiment
0    False      False
1    False      False
2    False      False
3    False      False
4    False      False
..     ...        ...
495  False      False
496  False      False
497  False      False
498  False      False
499  False      False

[500 rows x 9 columns]>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
# 1.Load Data

df = pd.read_csv('/content/Political Sentiment Analysis.csv') # Replace with your actual CSV file path
print("Original Data Shape:", df.shape)
print(df.head())

Original Data Shape: (500, 9)
   tweet_id     user_handle            timestamp  \
0         1        @user123  2024-11-03 08:45:00
1         2    @politicsFan  2024-11-03 09:15:23
2         3  @greenAdvocate  2024-11-03 10:05:45
3         4     @indieVoice  2024-11-03 11:20:10
4         5   @libertyLover  2024-11-03 12:35:55

                                          tweet_text       candidate  \
0  Excited to see Kamala Harris leading the Democ...   Kamala Harris
1  Donald Trump's policies are the best for our e...    Donald Trump
2  Jill Stein's environmental plans are exactly w...      Jill Stein
3  Robert Kennedy offers a fresh perspective outs...  Robert Kennedy
4  Chase Oliver's libertarian stance promotes tru...    Chase Oliver

               party  retweets  likes sentiment
0   Democratic Party       120    450  positive
1   Republican Party        85    300  positive
2        Green Party        60    200  positive
3        Independent        40    150   neutral
4  Libertarian Party        30    120  positive

In [5]:
# 2.Basic Info

print("\nData Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())

Data Types:
 tweet_id        int64
user_handle    object
timestamp      object
tweet_text     object
candidate      object
party          object
retweets        int64
likes           int64
sentiment      object
dtype: object

Missing Values:
 tweet_id       0
user_handle    0
timestamp      0
tweet_text     0
candidate      0
party          0
retweets       0
likes          0
sentiment      0
dtype: int64

In [12]:
# 3.Handle Missing Values

# Separate numerical and categorical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Numerical: Replace with mean
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Categorical: Replace with mode
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [11]:
# 4.Encode Categorical Variables

# Identify columns to one-hot encode based on expected features for X and y
ohe_cols = ['candidate', 'party', 'sentiment']

# Drop columns not intended for use in X or Y that are still in object format
# (e.g., identifiers like tweet_id or text fields)
df = df.drop(columns=['tweet_id', 'user_handle', 'timestamp', 'tweet_text'], errors='ignore')

# Perform One-hot Encoding for the specified categorical columns
# drop_first=True prevents multicollinearity by dropping one of the dummy variables.
df = pd.get_dummies(df, columns=ohe_cols, drop_first=True)

# No separate Label Encoding needed for binary categoricals if they are part of ohe_cols

In [16]:
# 5.Outlier Detection and Treatment (using IQR)

for col in num_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df[col] = np.where(df[col] < lower, lower, df[col])
df[col] = np.where(df[col] > upper, upper, df[col])

In [17]:
# 6.Feature Scaling

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [43]:
target_col = 'sentiment'  # Replace with your actual target column name

if target_col in df.columns:
    X = df.drop(target_col, axis=1)
    y = df[target_col]

    bestfeatures = SelectKBest(score_func=f_classif, k=10)
    fit = bestfeatures.fit(X, y)

    selected_features = X.columns[fit.get_support()]
    df = df[selected_features.to_list() + [target_col]]

    print("\nSelected Features:", selected_features.to_list())

corr.sort_values(by='sentiment_neutral', ascending=False)

,retweets,candidate_Donald Trump,candidate_Jill Stein,candidate_Kamala Harris,candidate_Robert Kennedy,party_Green Party,party_Independent,party_Libertarian Party,party_Republican Party,sentiment_neutral,sentiment_positive
sentiment_neutral,-0.491767,0.009213,-0.290215,-0.290215,0.861431,-0.290215,0.861431,-0.290215,0.009213,1.000000,-0.801534
candidate_Robert Kennedy,-0.710715,-0.250000,-0.250000,-0.250000,1.000000,-0.250000,1.000000,-0.250000,-0.250000,0.861431,-0.690467
party_Independent,-0.710715,-0.250000,-0.250000,-0.250000,1.000000,-0.250000,1.000000,-0.250000,-0.250000,0.861431,-0.690467
candidate_Donald Trump,0.619663,1.000000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,1.000000,0.009213,-0.385230
party_Republican Party,0.619663,1.000000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,1.000000,0.009213,-0.385230
party_Libertarian Party,-0.367240,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,1.000000,-0.250000,-0.290215,0.351549
candidate_Jill Stein,0.054429,-0.250000,1.000000,-0.250000,-0.250000,1.000000,-0.250000,-0.250000,-0.250000,-0.290215,0.362074
party_Green Party,0.054429,-0.250000,1.000000,-0.250000,-0.250000,1.000000,-0.250000,-0.250000,-0.250000,-0.290215,0.362074
candidate_Kamala Harris,0.403863,-0.250000,-0.250000,1.000000,-0.250000,-0.250000,-0.250000,-0.250000,-0.250000,-0.290215,0.362074
retweets,1.000000,0.619663,0.054429,0.403863,-0.710715,0.054429,-0.710715,-0.367240,0.619663,-0.491767,0.207651
sentiment_positive,0.207651,-0.385230,0.362074,0.362074,-0.690467,0.362074,-0.690467,0.351549,-0.385230,-0.801534,1.000000

In [12]:
import numpy as np
import sklearn.preprocessing as preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = np.asarray(df[['retweets', 'likes', 'candidate_Donald Trump', 'candidate_Jill Stein','candidate_Kamala Harris', 'candidate_Robert Kennedy', 'party_Green Party', 'party_Independent', 'party_Libertarian Party', 'party_Republican Party']])
y = np.asarray(df['sentiment_positive'])

# Scale the features using preprocessing.StandardScaler()
X = preprocessing.StandardScaler().fit(X).transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size = 0.3, random_state = 4)

print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (350, 10) (350,)
Test set: (150, 10) (150,)

In [13]:
#Classification Models :

#1.Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9333333333333333

In [14]:
#2.K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.98

In [15]:
#3.Decision Tree
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.98

In [16]:
#4.Random Forest
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.98

In [17]:
#5.Support Vector Machine
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9333333333333333

In [18]:
#6.Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.98

In [19]:
#7.Naive Bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9333333333333333